### ISSUE TITLE
Toggling between Start and End in switcher doesn't work first time

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#6]
When the control comes up first. Click a new start date, the triangle doesn't slide from Start to End. Click a new start date again and this time it does.

Also, when it does slide over and you select a end date, it doesn't slide back to Start.

**Comment by rapuckett** [comment]
"Click a new start date, the triangle doesn't slide from Start to End."

Could not repro this. If issue persists could you please provide exact steps to reproduce? (did you tap on current day? A day in the past? etc).

"when it does slide over and you select a end date, it doesn't slide back to Start."

This behavior is not built directly into the DurationPicker control because the Mode Selector is only there to help demonstrate functionality. It's not part of the DurationPicker control.

This can, however, be accomplished by overriding the durationPicker:endDateChanged: and durationPicker:startDateChanged: methods from `CXDurationPickerViewDelegate`. Any action can then be performed, such as changing the mode in the Mode Switcher. I'll update docs to be more clear.

With respect to the demo project, this could be achieved with the following:

``` objective-c
- (void)durationPicker:(CXDurationPickerView *)durationPicker endDateChanged:(CXDurationPickerDate)pickerDate {
    [self.switcher setEndDateString:[CXDurationPickerUtils stringFromPickerDate:pickerDate]];
    [self.switcher setMode:CXDurationPickerModeStartDate];
}

- (void)durationPicker:(CXDurationPickerView *)durationPicker startDateChanged:(CXDurationPickerDate)pickerDate {
    [self.switcher setStartDateString:[CXDurationPickerUtils stringFromPickerDate:pickerDate]];
    [self.switcher setMode:CXDurationPickerModeEndDate];
}
```

**Comment by bixbarton** [comment]
It can't be repro'd in the demo, only in Jarvis. However, the reason seems to be that when you select a new start date in the future, it fires invalidStartDateSelected, rather than startDateChanged. I wonder if the condition that triggers invalidStartDateSelected needs reviewing, so that it doesn't treat a new start date in the future as invalid? Perhaps we need a new invalid, and we need to treat this situation as a new event?

Moved to new issue #17
